ARG python_version
FROM elifesciences/python_3.6_pipenv:${python_version}

ARG pipenv_dev_arg

ENV PROJECT_FOLDER=/srv/digests
WORKDIR ${PROJECT_FOLDER}

# TODO: possibly simplify this to use only pipenv rather than virtualenv?
RUN virtualenv venv --python=python3.6
ENV VIRTUAL_ENV=${PROJECT_FOLDER}/venv

COPY Pipfile Pipfile.lock ./
RUN pipenv install ${pipenv_dev_arg} --deploy
