version: '3'

services:
    web:
        image: nginx:1.25.1
        ports:
            - "8080:80"
        volumes:
            - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - wsgi
    wsgi:
        build:
            target: dev
            context: .
        command: >
            bash -c "./migrate.sh && exec venv/bin/uwsgi --ini=/srv/digests/uwsgi.ini --enable-threads"
        volumes:
            - ./config/uwsgi.ini:/srv/digests/uwsgi.ini
        env_file:
            - dev.env
        depends_on:
            - db
    db:
        image: postgres:9.4
        volumes:
            - ./config/application_user.sql:/docker-entrypoint-initdb.d/application_user.sql
        ports:
            - '5432:5432'
        env_file:
            - dev.env
    goaws:
        image: elifesciences/goaws:1.0.1
        ports:
            - 4100:4100
        volumes:
            - ./config/goaws.yaml:/conf/goaws.yaml
