# Generated by Django 2.0.7 on 2018-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
