# Generated by Django 3.2.13 on 2022-05-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_auto_20180801_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digest',
            options={'ordering': ('-published', '-id')},
        ),
        migrations.AlterField(
            model_name='digest',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='digest',
            name='image',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='digest',
            name='relatedContent',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='digest',
            name='subjects',
            field=models.JSONField(null=True),
        ),
    ]
