# Generated by Django 2.0.7 on 2018-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_auto_20180726_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='stage',
            field=models.CharField(choices=[('preview', 'preview'), ('published', 'published')], default='preview', max_length=25),
        ),
    ]
