# Generated by Django 2.0.7 on 2018-07-31 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0003_digest_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digest',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterField(
            model_name='digest',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
