# Generated by Django 2.0.7 on 2018-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0005_auto_20180731_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
