name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      trunkver: ${{ steps.trunkver.outputs.trunkver }}
    steps:
      - name: Get a version tag
        id: trunkver
        uses: crftd-tech/trunkver@main
        with:
          prerelease: ${{ github.ref == 'refs/heads/master' && 'false' || 'true' }}
      - run: echo ${{ steps.trunkver.outputs.trunkver }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Project Tests
        run: make ci-test
      - name: Smoketest
        run: make ci-smoketest
  build-and-push:
    needs: [generate-version, tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      IMAGE_REPO: ghcr.io/elifesciences/digests
      IMAGE_TAG: ${{ needs.generate-version.outputs.trunkver }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          load: false
          # Disabled until another image with ARM support can be used as a base
          # platforms: linux/amd64,linux/arm64
          target: prod
          file: Dockerfile.multistage
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
